### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by aaronmusknew** [Nik-Hendricks/node.js-sip#3]
I really need this module working making calls being able to hear and send audio and DTMF

The only module I found that managed to connect my sip via UDP was yours

Send me your patreon I can help I need a functional version to do the functions I mentioned above

**Comment by Nik-Hendricks** [comment]
Alot of updates are coming do not worry. I plan on adding a class for Extracting DTMF once i get RTP streaming fully working. I will be updating the Readme as well to reflect new additions I have made. Stay tuned.

**Comment by Nik-Hendricks** [comment]
Hello, If you take a look at the examples. Last night i was able to get RTP streaming working. So far it has been test with Zoiper softphones and Yealink SIP phones. I will be implementing DTMF detection soon hopefully within the next two nights.

**Comment by aaronmusknew** [comment]
Hey bro do you have discord?

**Comment by aaronmusknew** [comment]
Proxy authorization is also interesting to implement

**Comment by Nik-Hendricks** [comment]
That will be coming soon as well. I plan on fully supporting rfc 3261. also my discord is Nightcrawler#2268

**Comment by aaronmusknew** [comment]
Add Yoshi

**Comment by aaronmusknew** [comment]
Hey bro accept my friend request on discord my discord is Yoshi i have a proposal for you.

**Comment by volkankoc** [comment]
> That will be coming soon as well. I plan on fully supporting rfc 3261. also my discord is Nightcrawler#2268

ok my discord is _volkankoc. I am waiting invite
