### ISSUE TITLE
How can I tell if the call has ended

### ISSUE THREAD

**Issue by volkankoc** [Nik-Hendricks/node.js-sip#4]
Hi  i need to call end detail

How can I tell if the call has ended ?

thank u

**Comment by volkankoc** [comment]
Also , How can I end a call

**Comment by volkankoc** [comment]
@Nik-Hendricks

**Comment by Nik-Hendricks** [comment]
Hello @volkankoc if you would take a look at the examples folder. I have a few demonstrations on how you can do this. In short you could use the `SIP.on` method. and listen for either a `CANCEL` or `BYE` message.

**Comment by volkankoc** [comment]
I solved the problem. But in a different way.
into SIP.js new function
` send3(callid) {
     
        const constructed_message='BYE sip:104@192.168.2.106 SIP/2.0\r\n'+
        'Via: SIP/2.0/UDP 192.168.2.103:54003;branch=z9hG4bK.YZHIky4GT;rport\r\n'+
        'From: <sip:103@192.168.2.106>;tag=h90B~eR\r\n'+
        'To: <sip:104@192.168.2.106>;tag=b0d2603d03bedc6e\r\n'+
        'CSeq: 111 BYE\r\n'+
        'Call-ID:'+callid+'\r\n'+
        'Max-Forwards: 70\r\n'+
        'User-Agent: Linphone-Desktop/5.0.17 (volkan-MacBook-Air.local) osx/13.4 Qt/5.15.2 LinphoneSDK/5.2.66-2-g24e7882ce\r\n'+ 
        '\r\n';

                this.Socket.send(constructed_message, 0, constructed_message.length, Number("5060"), "192.168.2.106", (error) => {
                                    
                    })             
            }`
Now I have a different problem dtmf. Will you be working on DTMF? I'm looking forward to. Also, I added you on discord. Do you agree @Nik-Hendricks

**Comment by Nik-Hendricks** [comment]
@volkankoc Yes DTMF is coming in the near future. As well as some larger improvements to the library. Feel free to leave me any suggestions or feature requests on my discord.
