### ISSUE TITLE
Does this package support RTP?

### ISSUE THREAD

**Issue by Syed-AliHamza** [Nik-Hendricks/node.js-sip#6]
I'm interested in discussing the flow of SIP routers with SIP agents and their implementation. Could we schedule a brief meeting on Google Meet to go over this topic? I believe a real-time conversation would be more effective.

**Comment by mo-g** [comment]
Apparently? https://github.com/Nik-Hendricks/node.js-sip/blob/main/RTP.js

I need to grab a couple more hardware parts for what I'm working on, but I'll be testing this out over the next few days. I was working on an RTP implementation for NodeJS a year or so back (https://github.com/Combadge/Spindoctor/tree/mantissa/Libraries/ecma-rtp) but this looks rather more likely to be functional than mine - I did the usual "too much, too soon" approach.

**Comment by Nik-Hendricks** [comment]
That is almost what happened to my approach. Also why The latest is not pushed. I have a far better ground-up RTP implementation as well as a better SIP message parser. The engineering of how the Libraries play together has been improved as well. I will push the updated branch eventually. But it is more of a VOIP framework now.

**Comment by mo-g** [comment]
Works for me! I have three purposes for this: underlying transport for a DIY SIP phone, external interfacing for a Combadge server, and I also need a decent RTP layer to actually talk with the badges. So I'll be interested to see what "node.js-voip" looks like. :D
